---
- name: insert unbound_flags="" in /etc/rc.conf.local
  lineinfile:
    state: present
    path: /etc/rc.conf.local
    regexp: '^unbound_flags='
    line: 'unbound_flags=""'
  register: unboundflags
  become: yes

- name: copy unbound conf
  template:
    src: unbound.conf.j2
    dest: /var/unbound/etc/unbound.conf
    owner: root
    group: wheel
    mode: "0644"
  register: unboundconf
  become: yes

- name: enable unbound
  shell: rcctl enable unbound
  when: unboundconf.changed or unboundflags.changed
  become: yes

- name: check unbound is running
  shell: rcctl check unbound
  register: unboundisup
  ignore_errors: True
  become: yes

- name: start unbound
  shell: rcctl start unbound
  when: unboundisup.rc|int != 0
  register: startunbound
  become: yes

- name: restart unbound
  shell: rcctl restart rad
  when: unboundisup.rc|int == 0 and (unboundflags.changed or unboundconf.changed)
  register: restartunbound
  become: yes
