---
- name: touch file /etc/rc.conf.local
  file:
    dest: /etc/rc.conf.local
    owner: root
    group: wheel
    state: touch
  become: yes

- name: insert dhcp6c_flags=cnmac0 in /etc/rc.conf.local
  lineinfile:
    state: present
    dest: /etc/rc.conf.local
    regexp: '^dhcp6c_flags='
    line: 'dhcp6c_flags=cnmac0'
  become: yes

- name: insert dhcp6c restart in /etc/hostname.cnmac0
  lineinfile:
    state: present
    dest: /etc/hostname.cnmac0
    insertafter: EOF
    line: '!/usr/sbin/rcctl restart dhcp6c'
  become: yes

- name: copy dhcp6c.conf
  template:
    src: dhcp6c.conf.j2
    dest: /etc/dhcp6c.conf
  become: yes

- name: copy dhcp6c
  template:
    src: dhcp6c.j2
    dest: /etc/rc.d/dhcp6c
    mode: "0555"
  become: yes

- name: enable dhcp6c
  shell: rcctl enable dhcp6c
  become: yes

- name: restart dhcp6c
  shell: rcctl restart dhcp6c
  become: yes
