---
- name: copy resolv.conf.tail
  template:
    src: resolv.conf.tail.j2
    dest: /etc/resolv.conf.tail
  become: yes

- name: touch file /etc/sysctl.conf
  file:
    dest: /etc/sysctl.conf
    owner: root
    group: wheel
    state: touch
  become: yes

- name: insert net.inet.ip.forwarding=1 in /etc/sysctl.conf
  lineinfile:
    state: present
    path: /etc/sysctl.conf
    regexp: '^net.inet.ip.forwarding=1'
    line: 'net.inet.ip.forwarding=1'
  register: ipv4forward
  become: yes

- name: insert net.inet6.ip6.forwarding=1 in /etc/sysctl.conf
  lineinfile:
    state: present
    path: /etc/sysctl.conf
    regexp: '^net.inet6.ip6.forwarding=1'
    line: 'net.inet6.ip6.forwarding=1'
  register: ipv6forward
  become: yes

- name: load newly added sysctl values
  shell: xargs sysctl < /etc/sysctl.conf
  when: ipv4forward.changed or ipv6forward.changed
  become: yes

- name: insert rad_flags="" in /etc/rc.conf.local
  lineinfile:
    state: present
    path: /etc/rc.conf.local
    regexp: '^rad_flags='
    line: 'rad_flags='
  register: radflags
  become: yes

- name: copy rad conf
  template:
    src: rad.conf.j2
    dest: /etc/rad.conf
    owner: root
    group: wheel
    mode: "0644"
  register: radconf
  become: yes

- name: enable rad
  shell: rcctl enable rad
  when: radflags.changed or radconf.changed
  become: yes

- name: check rad is running
  shell: rcctl check rad
  register: radisup
  ignore_errors: True
  become: yes

- name: start rad
  shell: rcctl start rad
  when: radisup.rc|int != 0
  register: startrad
  become: yes

- name: restart rad
  shell: rcctl restart rad
  when: radisup.rc|int == 0 and (radflags.changed or radconf.changed)
  register: restartrad
  become: yes

# This may not actually be needed because OpenBSD moved away from rtadvd to rad
# Adding it here because of superstitious reasons because adding this file
# appeared to make IPv6 prefix delegation and SLAAC work on the LAN
- name: touch /etc/rtadvd.conf
  file:
    path: /etc/rtadvd.conf
    state: touch
    owner: root
    group: wheel
    mode: '0664'
  become: yes
