---
- name: install dhcpcd
  openbsd_pkg:
    state: latest
    name: dhcpcd
  become: yes

- name: install curl
  openbsd_pkg:
    state: latest
    name: curl
  become: yes

# ntpd doesn't start if ntpd_flags=YES is in /etc/rc.conf.local
- name: remove ntpd_flags=YES from /etc/rc.conf.local
  lineinfile:
    state: absent
    path: /etc/rc.conf.local
    regexp: '^ntpd_flags=YES'
  become: yes

- name: enable ntpd
  shell: rcctl enable ntpd
  become: yes
